### ISSUE TITLE
wand crashing when window resized

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/wand#48]
```
WARNING:wand.tools:Unable to find server configuration file, restoring from backup
Traceback (most recent call last):
  File "C:\Users\ThomasHarty\miniconda3\envs\wand\lib\site-packages\pyqtgraph\widgets\VerticalLabel.py", line 52, in paintEvent
    self.hint = p.drawText(rgn, align, self.text())
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'QRect'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, QRect, int, str): argument 2 has unexpected type 'Alignment'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'QRect'
  drawText(self, QPoint, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, int, int, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, str): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\ThomasHarty\miniconda3\envs\wand\lib\site-packages\pyqtgraph\widgets\VerticalLabel.py", line 52, in paintEvent
    self.hint = p.drawText(rgn, align, self.text())
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'QRect'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, QRect, int, str): argument 2 has unexpected type 'Alignment'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'QRect'
  drawText(self, QPoint, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, int, int, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, str): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\ThomasHarty\miniconda3\envs\wand\lib\site-packages\pyqtgraph\widgets\VerticalLabel.py", line 52, in paintEvent
    self.hint = p.drawText(rgn, align, self.text())
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'QRect'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, QRect, int, str): argument 2 has unexpected type 'Alignment'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'QRect'
  drawText(self, QPoint, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, int, int, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, str): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\ThomasHarty\miniconda3\envs\wand\lib\site-packages\pyqtgraph\widgets\VerticalLabel.py", line 52, in paintEvent
    self.hint = p.drawText(rgn, align, self.text())
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'QRect'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, QRect, int, str): argument 2 has unexpected type 'Alignment'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'QRect'
  drawText(self, QPoint, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, int, int, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, str): argument 1 has unexpected type 'QRect'
Traceback (most recent call last):
  File "C:\Users\ThomasHarty\miniconda3\envs\wand\lib\site-packages\pyqtgraph\widgets\VerticalLabel.py", line 52, in paintEvent
    self.hint = p.drawText(rgn, align, self.text())
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'QRect'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, QRect, int, str): argument 2 has unexpected type 'Alignment'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'QRect'
  drawText(self, QPoint, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, int, int, int, str): argument 1 has unexpected type 'QRect'
  drawText(self, int, int, str): argument 1 has unexpected type 'QRect'
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPaintDevice: Cannot destroy paint device that is being painted
```

**Comment by hartytp** [comment]
https://github.com/pyqtgraph/pyqtgraph/blob/7f7c6217cc2fae5fdfad6d3c27739461abd32c84/pyqtgraph/widgets/VerticalLabel.py#L52

**Comment by hartytp** [comment]
```
>conda list
# packages in environment at C:\Users\ThomasHarty\miniconda3\envs\wand:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.21.4          py310h5ebf175_0    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3          py310h5588dad_8    conda-forge
pyqt-impl                 5.12.3          py310h8a704f9_8    conda-forge
pyqt5-sip                 4.19.18         py310h8a704f9_8    conda-forge
pyqtchart                 5.12            py310h8a704f9_8    conda-forge
pyqtgraph                 0.12.3             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1          py310h8a704f9_8    conda-forge
python                    3.10.0          h9a09f29_3_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
qasync                    None            py38_0+gita0d4249    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
qt                        5.12.9               h5909a2a_4    conda-forge
scipy                     1.7.3           py310h33db832_0    conda-forge
setuptools                59.2.0          py310h5588dad_0    conda-forge
sipyco                    1.1             py38_35+git9ec4e36    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wand-client               v1.0            py38_161+git43864e4    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
```

**Comment by hartytp** [comment]
hmmm...alignment should be an int. See usage in https://doc.qt.io/qt-5/qpainter.html#drawText

Typing error? Something to do with a recent change to pyqtgraph?

**Comment by hartytp** [comment]
here is a conda environment which doesn't have this problem

```
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.12.8            haa95532_0
certifi                   2020.12.5        py38haa95532_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
intel-openmp              2020.2                      254
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.37               h2a8f88b_0
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
openssl                   1.1.1i               h2bbff1b_0
pip                       20.3.3           py38haa95532_0
pyqt                      5.9.2            py38ha925a31_4
pyqtgraph                 0.11.0                     py_0
python                    3.8.5                h5fd99cc_1
qasync                    None            py38_0+gitce95ce9    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
qt                        5.9.7            vc14h73c81de_0
scipy                     1.5.2            py38h14eb087_0
setuptools                51.1.2           py38haa95532_4
sip                       4.19.13          py38ha925a31_0
sipyco                    1.1             py38_21+gitbcc11ad    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
six                       1.15.0           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wand-client               v1.0            py38_130+gitb8aeb02    https://condafeedwin.azurewebsites.net/xVVr5vkQoSF0U4GJSK5e
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4
```

**Comment by hartytp** [comment]
seems like putting python to 3.85 fixes it.

**Comment by lochsh** [comment]
See https://github.com/pyqtgraph/pyqtgraph#qt-bindings-test-matrix

**Comment by dnadlinger** [comment]
Not reproduced in recent memory, and potentially seems related to pyqtgraph version issues. Closing purely for triage reasons.
